#!/usr/bin/perl -w
# Generate usys.S - user-space syscall stubs

print "# usys.S - generated by usys.pl - DO NOT EDIT\n";
print ".text\n";
print "# Each SYSCALL(name) generates a user-space stub\n\n";

# Only these two includes — DO NOT include user.h
print "#include \"syscall.h\"\n";
print "#include \"traps.h\"\n\n";

# Define the syscall stub macro
print "#define SYSCALL(name) \\\n";
print "  .globl name; \\\n";
print "  name: \\\n";
print "    movl \$SYS_##name, %eax; \\\n";
print "    int  \$T_SYSCALL; \\\n";
print "    ret\n\n";

sub entry {
    my $name = shift;
    print "SYSCALL($name)\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("shutdown");

